### ISSUE TITLE
Height offset in SquidPanel::tint

### ISSUE THREAD

**Issue by smelc** [SquidPony/SquidLib#119]
In [Dungeon Mercenary](http://www.schplaf.org/hgames), `SquidPanel::tint` is off by 2 pixels as shown in the image below (zoom on the red cell close to the '@'). I circumvent the bug with this patch:

```{.java}
git diff squidlib/src/main/java/squidpony/squidgrid/gui/gdx/TextCellFactory.java
diff --git a/squidlib/src/main/java/squidpony/squidgrid/gui/gdx/TextCellFactory.java b/squidlib/src/main/java/squidpony/squidgrid/gui/gdx/TextCellFactory.java
index 68438a3..cc3570d 100644
--- a/squidlib/src/main/java/squidpony/squidgrid/gui/gdx/TextCellFactory.java
+++ b/squidlib/src/main/java/squidpony/squidgrid/gui/gdx/TextCellFactory.java
@@ -946,7 +946,7 @@ public class TextCellFactory implements Disposable {
         } else if(s.length() > 0 && s.charAt(0) == '\0') {
             Image im = new Image(block);
             im.setColor(scc.filter(color));
-            im.setSize(width * s.length(), height);
+            im.setSize(width * s.length(), height + 2);
             // im.setPosition(x - width * 0.5f, y - height * 0.5f, Align.center);
             return im;
         } else {
```
![tint-bug](https://cloud.githubusercontent.com/assets/634720/13731627/1c603078-e96e-11e5-8341-a3408de7ce78.png)

In this static screenshot, the bug doesn't catch the eye; but it is clearly visible "live", because of the "top" offset (i.e. at the top of cell) that leaves a 2 pixels black bar.

This bug is weird, because my workaround is in a method that has a lot of callers (`TCF::makeActor`), so it should affect other methods; but I only witness it with `tint` (it should be noted that I do not use many animations, neither AnimatedEntities, so maybe I'm missing them).

**Comment by SquidPony** [comment]
is this due to the height push by one pixel to get line drawing vertical characters to line up?

**Comment by smelc** [comment]
Where was this change done ? Because I'm slightly late w.r.t. to SquidLib's master branch. I'm working on https://github.com/SquidPony/SquidLib/commit/f5879e9b7f281b548438433293db8944d39e5ae1 (11 days ago at the time of writing).

**Comment by tommyettinger** [comment]
I haven't changed tint in the last (much more than) 11 days, but I have changed TextCellFactory. I think I noticed this in a different context for the AnimatedEntity objects I use for animating movement in EverythingDemo; they seemed too low, as this seems to confirm. I actually noticed this quite a long time ago but had no way to prove to myself that it was an actual bug; I'll check all the places this could be affected, but I suspect it has to do with the descent on the BitmapFont being taken into account in some places but not others. This should be a simple fix if that's the only cause... @smelc, can you perhaps check the BitmapFont (used in the grid for that image) for what `.getDescent()` returns? If it's 2 or getting rounded/floored to 2, that would explain quite a lot.

**Comment by tommyettinger** [comment]
I think this is fixed as of the latest commit, https://github.com/SquidPony/SquidLib/commit/ef9ed26aca2b55ae5fa1e6ee073bbc00a15ad941 , but I can't be quite sure yet. There may still be a 1px offset with some fonts at some sizes, to height and/or width. I think the issue is related to the descent being taken into account when drawing fonts, but not when making them into Actors, which `tint()` does to the background block.

**Comment by smelc** [comment]
In fact, I've had this problem for a very long time, since the start of Dungeon Mercenary if I recall correctly. The font I use has a descent of -6.0 (it is @tommyettinger's Inconsolata font). After ef9ed26, the problem is worse :-( as the attached image demonstrates.
![dm-tint-problem-tommys-trial](https://cloud.githubusercontent.com/assets/634720/13790420/a2ec0eb6-eae8-11e5-95a5-758a7a5b6cf9.png)

**Comment by tommyettinger** [comment]
OK, this seems to be only related to when a cell background is turned into an Actor (done to animate tint, fade, move, etc. effects), since only some of the cells are offset or maybe shortened vertically, and they're all near the green effect (did the smoke bomb or any other animation previously affect the other cells to the left and above that now have a black over-bar?). It also doesn't seem to involve any horizontal placement issues, only vertical (and the amount of offset seems different based on where the cell is on the screen). The last part is the one that is most troubling, since I can't recall anywhere that the y position in cells should affect the offset to the y position in pixels.

I just did some investigating and it looks like the recently-added actualCellHeight field in TextCellFactory objects varies between distance field and non-distance field fonts. I just pushed a commit that removes this different treatment, and now it seems to look the same (and correct, filling a cell exactly with a tint) in EverythingDemo with distance field fonts and SquidAIDemo with normal bitmap fonts

As an aside, is this a modified version of Inconsolata you're using? The lower-case `l` letter seems very different, as does the `@`.

**Comment by smelc** [comment]
There are cells with just a black bar, because the bomb exploded in the middle, and I tint randomly the nine cells around the bomb, with a small delay in between every of them. Interestingly, the black bars appear _before_ tinting. I agree that the amount of offset varying is very weird. Actually, I don't remember seeing that before your last update that I tried (ef9ed26).

I've posted the video from which I extracted the screenshot here: https://vid.me/mroX You can see the bars appearing, and the offset variations.

@tommyettinger> I'll keep you posted on trying the update you mention in your last comment.

ps: I'm using Inconsolat-LGC.ttf

**Comment by smelc** [comment]
Still the same behavior as the previous video with fefa7c33a0741e2211bec6c420c13569b639072e :-(

**Comment by tommyettinger** [comment]
OK, definitely an actor height or actor y-position issue; when the tint ends it recalls the actor, which deletes the actor and replaces its position with normal text in the SquidPanel. It seems like the black bar appears only while the tint is happening (and/or a delay is occurring before the tint, which also means it's working on an Actor). Debugging this would probably be able to show the actual height of the Actor during a tint (setting a breakpoint in SquidPanel's tint method would be good), and you can compare it to the intended height of a cell. If the intended cell height and the height of the Actor are the same, then it's definitely a position issue. If the height is shorter, then it could instead/also involve an incorrectly-sized block Texture being used for the tinting background. The position problem would be a little harder to resolve, since there are cases where we use AnimatedEntity and cases where we use plain Actor (such as Label or Image; one function can return either since they're both Actors), and Actor doesn't have a way to offset the position where someone requests it to draw. It's possible both issues could be fixed in the same way, by adjusting the height of the Actor to larger than the height of a cell but only filling the cell-sized part of it with color.

**Comment by tommyettinger** [comment]
OK, this one was uh... more work, and less of that was smart work. I sorta had to use trial-and-error for the different possible ways I could move a font more in some cases and less in others, but https://github.com/SquidPony/SquidLib/commit/81257292f17b7d34ba84c12b3ebcde669908e6f8 should get closer to fixing something in some cases... I've pretty much reworked every part of how SquidPanel and TextCellFactory work together for positioning. I may have changed some minor recent API stuff... So this may have added some bugs, but it should fix this devilish one here.

**Comment by smelc** [comment]
This is worse now :-( The menus are broken and there are black bars on the map. See: https://vid.me/PAcz

I've checked the height of the actor (`a` in the code) and it is correct: it is the same as the cell's height (34). Here's the state of the actor at `tint`'s entry: ![tint-debug-state](https://cloud.githubusercontent.com/assets/634720/13856021/8a04936e-ec73-11e5-9177-4b197bef0215.png)

Hope this helps and thanks for your help!

**Comment by smelc** [comment]
I've tried with 331475c24314f29833f4916f5b803c1d6253a932 and the tint bug is still there, but other artefacts disappeared. I think it's better than the initial version; since the offset is only one pixel high (it seems two, but I believe one pixel comes from the different fog of wars between adjacent cells): 
![tint-almost-there](https://cloud.githubusercontent.com/assets/634720/13872297/c903c000-ece9-11e5-84dc-5a164e43e000.png)

And here's the video: https://vid.me/tSoZ

**Comment by tommyettinger** [comment]
5 minutes later, I have pushed a commit that seems to not interfere with the demos' display but should offset by 1px vertically. I believe the offset was also needed in my earlier code, but didn't ever appear in the demos because of the order in which I draw backgrounds (I think I was always drawing a background for the row below, going over the bottom of the cells in the row above, and Dungeon Mercenary may draw in the reverse order). Can you try it out if you get the chance?

**Comment by smelc** [comment]
@tommyettinger> awesome you fixed it!

I let you close the task. Thanks once again for your help !

**Comment by tommyettinger** [comment]
Woohoo! This has been a nasty bug, and it would have been especially bad if it made it into a stable release and individual-project workarounds became needed for anyone using effects like `tint()`. Instead, we have positions and sizes that should actually work for most fonts, even with the unusual things I've been testing against in EverythingDemo (drawing at 1x, 2x, and 3x sizes and scaling down by different x and y proportions, using a larger font than the cell, etc.). I'm glad you pointed out the issue and your fix! Fixing this pointed out a number of places where code could be improved in some way; I think now that the fundamental basis of the Actor code is stable, maybe some more effects could be added. Closing this issue now and feeling greatly relieved.
